import { CsvTable, Figure } from "@/components/ui";
import { applicationFigures } from "@/lib/content";

export default function ApplicationPage() {
  return (
    <div className="fade-in mx-auto max-w-6xl px-5 py-14">
      <p className="font-mono text-sm text-[#378ADD]">Application_2.ipynb</p>
      <h1 className="mt-3 text-4xl font-semibold">Seismic Hazard Quantization</h1>
      <p className="mt-5 max-w-3xl text-lg leading-8 text-[var(--muted)]">
        The application reproduces the regional seismic ground-motion example:
        Abrahamson-Silva 1997 median Sa maps, two strike-slip fault segments,
        triangular magnitude and depth distributions, and FQ-IDCVT quanta.
      </p>
      <section className="mt-10 rounded-md border border-[var(--line)] bg-[var(--panel)] p-6">
        <h2 className="text-2xl font-semibold">Why this application matters</h2>
        <div className="mt-4 grid gap-5 text-sm leading-7 text-[var(--muted)] md:grid-cols-3">
          <p>
            The figures are not ornamental. They test whether a compressed set
            of weighted maps preserves exceedance contours, autocorrelation, and
            probability mass structure.
          </p>
          <p>
            That makes the page legible to two audiences at once: researchers
            can audit the math, and emergency-management readers can see what
            “representative scenarios” actually look like.
          </p>
          <p>
            The conclusion is deliberately sober: HQ is useful when the reduced
            ensemble keeps the spatial statistics that downstream loss models
            depend on.
          </p>
        </div>
      </section>
      <div className="mt-10 space-y-10">
        {applicationFigures.map(([filename, caption]) => (
          <Figure key={filename} filename={filename} alt={`${filename} generated by Application_2.ipynb.`} caption={caption} />
        ))}
      </div>
      <section className="mt-14 space-y-5">
        <h2 className="text-2xl font-semibold">Table S1 accuracy summary</h2>
        <CsvTable filename="table_S1_accuracy.csv" />
      </section>
      <section className="mt-14 rounded-md border border-[var(--line)] bg-[var(--panel)] p-6">
        <h2 className="text-2xl font-semibold">Application Conclusion</h2>
        <div className="mt-4 grid gap-5 text-sm leading-7 text-[var(--muted)] md:grid-cols-2">
          <p>
            Table S1 makes the compression story concrete: moving from N=50 to
            N=500 lowers the max exceedance error from 0.0549 to 0.0147 and the
            mean exceedance error from 0.0055 to 0.0014 in the executed
            notebook output.
          </p>
          <p>
            The autocorrelation diagnostic tells the same story. The N=500
            quantizer reduces max ACF error from 9.445% to 2.397%, which is the
            difference between a nice-looking reduced set and one that preserves
            spatial dependence well enough to defend.
          </p>
          <p>
            The application turns the benchmark into an engineering decision:
            keep enough scenarios to preserve spatial exceedance and
            autocorrelation, but not so many that every downstream loss analysis
            has to carry the full Monte Carlo ensemble.
          </p>
          <p>
            That is the practical promise of Hazard Quantization: fewer maps,
            weighted honestly, with the spatial statistics still visible.
          </p>
        </div>
      </section>
    </div>
  );
}
